name: Repository Events

on: 
  push:
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]

jobs:
    checkout-test:
        name: Checkout Test
        runs-on: ubuntu-latest
        steps:
            - name: Print Info
              run: |
                 echo $GITHUB_SHA
                 echo $GITHUB_REF
            - name: Checkout Repo
              uses: actions/checkout@v4