name: Manually Tiggered Workflow

on:
    workflow_dispatch:
        inputs:
            string: 
                description: A String input
                type: string
                required: true
                default: "BASED"
            environment:
                description: "Environment"
                type: environment
                required: true

jobs:
    log-info:
        name: Log  Info
        runs-on: ubuntu-latest
        steps:
            - name: Print info
              run: |
                echo $GITHUB_REF
                echo $GITHUB_SHA
                echo $GITHUB_ACTOR
            - name: Print input
              run: |
                echo "String Input: ${{ inputs.string }}"
                echo "Environment Input: ${{ inputs.environment }}"