name: Matrix

run-name: "The Matrix By ${{github.actor}}"

on:
    push:

jobs:
    node-matrix:
        name: Node Matrix 
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14, 15, 16]
        runs-on: ${{ matrix.os }}        
        steps:
            - name: Node Version
              run: node -v
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version}}
            - name: Node Version
              run: node -v