name: Stale Issues & Pull Requests

on:
  schedule:
     - cron: "0 14 * * *"
     - cron: "0/5 * * * *"
jobs:
    stale:
        name: Stale
        runs-on: ubuntu-latest
        steps:
            - name: Using Stale
              uses: actions/stale@v8
              with:
                stale-issue-message: "This is some message."
                days-before-stale: 1
                days-before-close: 5